/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManRole;

import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Menu.Menu;
import Business.Orders.Order;
import Business.Restaurant.Restaurant;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import static java.time.Clock.system;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class DeliveryManWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    String deliveryManName;
    Order order;
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public DeliveryManWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.system = business;
        this.deliveryManName = userAccount.getUsername();
      
        
        populateTable();
        DeliveryMan dm = system.getDeliveryManDirectory().findDeliveryMan(userAccount.getUsername());
        jLabel1.setText(String.valueOf(dm.getRatings()));
    }
    
    public void populateTable(){
        
        DefaultTableModel dtm = (DefaultTableModel) deliveryTable.getModel();
        dtm.setRowCount(0);
        
                 
        for(Order o : system.getOrderHistory().getOrderHisotry()){
            if(o.getDeliveryMan()!=null){
                if(o.getDeliveryMan().getDeliveryManName().equals(deliveryManName)){
                    Object row[] = new Object[6];
                    row[0] = o.getOrderID();
                    row[1] = o.getRestaurant().getName();
                    row[2] = o.getUserAccount().getUsername();
                    row[3] = o;
                    row[4] = o.getComments();
                    row[5] = o.getAmount();
                   // row[6] = 
                    dtm.addRow(row);
                }
            }else{
                System.out.println("Orders not found");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        deliveryTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assignJButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        assignJButton.setForeground(new java.awt.Color(0, 0, 0));
        assignJButton.setText("Assign to me");
        assignJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 190, 40));

        refreshJButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        refreshJButton.setForeground(new java.awt.Color(0, 0, 0));
        refreshJButton.setText("Refresh");
        refreshJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 160, 40));

        deliveryTable.setBackground(new java.awt.Color(241, 249, 251));
        deliveryTable.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        deliveryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Restaurant Name", "Customer Name", "Order Status", "Comments", "Total Value"
            }
        ));
        deliveryTable.setGridColor(new java.awt.Color(0, 0, 0));
        deliveryTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(deliveryTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 90, 720, 140));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("<<Ratings>>");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 150, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ratings");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 100, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Order Details");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 190, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        //        int selectedRow = workRequestJTable.getSelectedRow();
        //
        //        if (selectedRow < 0){
            //            return;
            //        }
        //
        //        WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        //        request.setReceiver(userAccount);
        //        request.setStatus("Pending");

        System.out.println("DDD ");
        int selectedRow1 = deliveryTable.getSelectedRow();
        if(selectedRow1 < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        order = (Order)deliveryTable.getValueAt(selectedRow1,3);
        System.out.println("Order "+ order.getOrderStatus());
        order.setOrderStatus("On the way");

        populateTable();

    }//GEN-LAST:event_assignJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JTable deliveryTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshJButton;
    // End of variables declaration//GEN-END:variables
}
